### ISSUE TITLE
Debug Backend Search and/or Add Form 

### ISSUE THREAD

**Issue by jschre01** [nattiecopeland/377ProjSong#25]
2 hours

**Comment by jschre01** [comment]
Jonathan attempted search page debug (and mostly failed) and perfected add song page debug for ~10 hours , Gregory perfected search page debug for (I assume) ~10 hours

**Comment by ghastings322** [comment]
I was working on other parts at the same time as this. This probably took about 5-6 hours, but it's hard to say for sure what pieces took what amount of time
