### ISSUE TITLE
Search Result Front end Page

### ISSUE THREAD

**Issue by nattiecopeland** [nattiecopeland/377ProjSong#8]

**Comment by jschre01** [comment]
1 hour

**Comment by jschre01** [comment]
Display search results on front end

**Comment by jschre01** [comment]
Added basic functionality, data is currently hard coded as a list, but can easily be changed if input list is changed to the list returned by backend search. Also, Fields in text can easily be changed when this page gets linked to home page

**Comment by jschre01** [comment]
Time: ~90 minutes (had to refamiliarize myself with React)
