### ISSUE TITLE
Front End Add Song Page

### ISSUE THREAD

**Issue by nattiecopeland** [nattiecopeland/377ProjSong#9]

**Comment by jschre01** [comment]
1 hour

**Comment by jschre01** [comment]
Create a form to add songs

**Comment by jschre01** [comment]
Created a form to add Songs. ***Note: Since we do not have a homepage yet I put this on the same page as the search results page, THIS IS TEMPORARY and will be moved as soon as the home page is set up. Additionally, currently the form doesn't submit as there is no database to add songs to yet.

**Comment by jschre01** [comment]
Time : ~ 1 hour
